- name: GNS3 EIGRP SPINE CONFIGURATION
  hosts: spr01.gns3lab-01
  gather_facts: false

  tasks:
  - name: configure ip interfaces
    cisco.ios.ios_l3_interfaces:
         config:
         - name: GigabitEthernet2/0
           ipv4:
           - address: 172.16.0.1/30

         - name: GigabitEthernet3/0
           ipv4:
           - address: 172.16.0.5/30

         - name: GigabitEthernet4/0
           ipv4:
           - address: 172.16.0.9/30

         - name: GigabitEthernet5/0
           ipv4:
           - address: 172.16.0.13/30
         state: merged
         
  - name: configure EIGRP 
    ios_config:
      lines:
      - passive-interface GigabitEthernet1/0
      - network 172.16.0.0 0.0.0.0
      - network 172.16.0.5 0.0.0.0
      - network 172.16.0.9 0.0.0.0
      - network 172.16.0.13 0.0.0.0
      parents: router eigrp 1
      
    
         
         
         

        
      
