- name: GNS3 SPR01 EIGRP CONFIGURATION 
  hosts: spr01.gns3lab-01
  gather_facts: false

  tasks:
  - name: configure ip interfaces
    cisco.ios.ios_l3_interfaces:
         config:
         - name: GigabitEthernet2/0
           ipv4:
           - address: 172.16.0.1/30

         - name: GigabitEthernet3/0
           ipv4:
           - address: 172.16.0.5/30

         - name: GigabitEthernet4/0
           ipv4:
           - address: 172.16.0.9/30

         - name: GigabitEthernet5/0
           ipv4:
           - address: 172.16.0.13/30
           
         - name: Loopback0
           ipv4:
           - address: 172.19.0.1/32 
         state: merged
         
  - name: configure eigrp 
    ios_config:
      lines:
      - passive-interface GigabitEthernet1/0
      - passive-interface Loopback0
      - network 172.16.0.0 0.0.0.0
      - network 172.16.0.5 0.0.0.0
      - network 172.16.0.9 0.0.0.0
      - network 172.16.0.13 0.0.0.0
      parents: router eigrp 1
      
  - name: bring ip interfaces up
  cisco.ios.ios_interfaces:
       config:
       - name: GigabitEthernet2/0 
         description: SPR-01 Gi2/0 to SPL-01 Gi1/0
         enabled: True
      


- name: GNS3 SPR02 EIGRP CONFIGURATION 
  hosts: spr02.gns3lab-01
  gather_facts: false

  tasks:
  - name: configure ip interfaces
    cisco.ios.ios_l3_interfaces:
         config:
         - name: GigabitEthernet2/0
           ipv4:
           - address: 172.16.0.21/30

         - name: GigabitEthernet3/0
           ipv4:
           - address: 172.16.0.29/30

         - name: GigabitEthernet4/0
           ipv4:
           - address: 172.16.0.33/30

         - name: GigabitEthernet5/0
           ipv4:
           - address: 172.16.0.37/30
           
         - name: Loopback0
           ipv4:
           - address: 172.19.0.2/32 
         state: merged
         
  - name: configure eigrp 
    ios_config:
      lines:
      - passive-interface GigabitEthernet1/0
      - passive-interface Loopback0
      - network 172.16.0.21 0.0.0.0
      - network 172.16.0.25 0.0.0.0
      - network 172.16.0.33 0.0.0.0
      - network 172.16.0.37 0.0.0.0
      parents: router eigrp 2
      
      
      
- name: GNS3 SPR03 EIGRP CONFIGURATION 
  hosts: spr03.gns3lab-01
  gather_facts: false

  tasks:
  - name: configure ip interfaces
    cisco.ios.ios_l3_interfaces:
         config:
         - name: GigabitEthernet2/0
           ipv4:
           - address: 172.16.0.41/30

         - name: GigabitEthernet3/0
           ipv4:
           - address: 172.16.0.45/30

         - name: GigabitEthernet4/0
           ipv4:
           - address: 172.16.0.49/30

         - name: GigabitEthernet5/0
           ipv4:
           - address: 172.16.0.53/30
           
         - name: Loopback0
           ipv4:
           - address: 172.19.0.3/32 
         state: merged
         
  - name: configure eigrp 
    ios_config:
      lines:
      - passive-interface GigabitEthernet1/0
      - passive-interface Loopback0
      - network 172.16.0.41 0.0.0.0
      - network 172.16.0.45 0.0.0.0
      - network 172.16.0.49 0.0.0.0
      - network 172.16.0.53 0.0.0.0
      parents: router eigrp 3
      
      
      
- name: GNS3 SPR04 EIGRP CONFIGURATION 
  hosts: spr04.gns3lab-01
  gather_facts: false

  tasks:
  - name: configure ip interfaces
    cisco.ios.ios_l3_interfaces:
         config:
         - name: GigabitEthernet2/0
           ipv4:
           - address: 172.16.0.57/30

         - name: GigabitEthernet3/0
           ipv4:
           - address: 172.16.0.61/30

         - name: GigabitEthernet4/0
           ipv4:
           - address: 172.16.0.65/30

         - name: GigabitEthernet5/0
           ipv4:
           - address: 172.16.0.69/30
           
         - name: Loopback0
           ipv4:
           - address: 172.19.0.4/32 
         state: merged
         
  - name: configure eigrp 
    ios_config:
      lines:
      - passive-interface GigabitEthernet1/0
      - passive-interface Loopback0
      - network 172.16.0.57 0.0.0.0
      - network 172.16.0.61 0.0.0.0
      - network 172.16.0.65 0.0.0.0
      - network 172.16.0.69 0.0.0.0
      parents: router eigrp 4 
      
    
         
    
         

        
      
